[package]
name = "helloworld"
version = "0.1.0"
resolver = "2"

[build-dependencies]

[dependencies]
nxdk-rs = { path = "../.." }
libc = "0.2.119"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
